[package]
name = "itualgs_rs"
version = "0.1.0"
edition = "2021"
authors = ["AlbertRossJoh, cave"]

[lib]
name = "itualgs_rs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
